apiVersion: v1
kind: Secret
metadata:
  name: dci-news-secret
  namespace: dci-news
  labels:
    app: whatisnews
type: Opaque
stringData:
  # Database
  POSTGRES_DB: "whatisnews"
  POSTGRES_USER: "whatisnews"
  POSTGRES_PASSWORD: "whatisnews123"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc.dci-news.svc.cluster.local:5432/whatisnews"
  SPRING_DATASOURCE_USERNAME: "whatisnews"
  SPRING_DATASOURCE_PASSWORD: "whatisnews123"
  # JWT
  JWT_SECRET: "WhatIsNews-JWT-Secret-Key-2024-Production"
  JWT_EXPIRATION: "86400000"
  # Admin
  ADMIN_DEFAULT_USERNAME: "admin"
  ADMIN_DEFAULT_PASSWORD: "admin123"
  # Upload
  FILE_UPLOAD_DIR: "/app/uploads"
